services:
  backend:
    build:
      context: ./coded-be
      dockerfile: Dockerfile
    volumes:
      - ./coded-be:/app
      - /app/.venv
      - db_data:/app/database
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  frontend:
    build:
      context: ./coded-fe
      dockerfile: Dockerfile
    volumes:
      - ./coded-fe:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_URL_API=http://localhost:8000
    depends_on:
      - backend

volumes:
  db_data: 