# Generated by Django 6.0.3 on 2026-03-28 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
            preserve_default=False,
        ),
    ]
