# Generated by Django 6.0.3 on 2026-03-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classgroup_delete_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='students',
        ),
    ]
