# Generated by Django 6.0.3 on 2026-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque como inativo para realizar exclusão lógica.', verbose_name='Ativo'),
        ),
    ]
