# Generated by Django 6.0.3 on 2026-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='localidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade'),
        ),
    ]
