# Generated by Django 6.0.3 on 2026-03-28 16:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato: (XX) 9XXXX-XXXX ou (XX) XXXX-XXXX.', regex='^\\(?([1-9]{2})\\)?[-. ]?9?[0-9]{4}[-. ]?[0-9]{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='localidade',
            field=models.CharField(default=1, max_length=255, verbose_name='Localidade'),
            preserve_default=False,
        ),
    ]
